---
Name: mysite
---
SilverStripe\View\SSViewer:
  themes:
    - '$default'
    - 'simple'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'mysite/javascript/googleanalytics.js'
SilverStripe\Security:
  default_login_dest: '/admin/pages'
SilverStripe\Assets\File:
  allowed_extensions:
    - 'html'
SilverStripe\CMS\Model\ErrorPage:
  enable_static_file: false
