---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
LeftAndMain:
  extra_requirements_javascript:
    - 'mysite/javascript/googleanalytics.js'
    - 'mysite/javascript/calltoaction.js'
  extra_requirements_css:
    - 'mysite/css/calltoaction.css'
SiteTree:
  nested_urls: true
MySQLDatabase:
  connection_charset: 'utf8'
Security:
  default_login_dest: '/admin/pages'
