version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/html/public/assets
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - directory
  - object: /var/www/html/public/assets
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: composer_setup.sh
      timeout: 300
      runas: root
